# Generated by Django 4.2.7 on 2024-01-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_details_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='Qulification',
            new_name='Qualification',
        ),
    ]
