# Generated by Django 4.2.7 on 2024-01-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_qulification_user_details_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='City',
            new_name='CurrentStatus',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='State',
            new_name='Institution',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Landmark',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Subject',
        ),
    ]
