# Generated by Django 4.2.7 on 2024-02-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='Teaching_status',
            field=models.BooleanField(default=False),
        ),
    ]
