# Generated by Django 4.2.7 on 2024-02-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_interests_teaching_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='Teaching_status',
            field=models.BinaryField(default=0),
        ),
    ]
