# Generated by Django 4.2.7 on 2024-02-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_interests_teaching_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='Teaching',
        ),
    ]
