# Generated by Django 4.2.7 on 2024-02-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_interests_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='Teaching_status',
            field=models.IntegerField(default=0),
        ),
    ]
