# Generated by Django 4.2.7 on 2024-02-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_alter_interests_teaching_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='teching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_status', models.IntegerField(default=0)),
                ('teach_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teachingBy', to=settings.AUTH_USER_MODEL)),
                ('teach_to', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teachingTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
