# Generated by Django 4.2.7 on 2024-02-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_teching'),
        ('user', '0016_auto_20240205_1700'),
    ]

    operations = [
    ]
