# Generated by Django 4.2.7 on 2024-02-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_merge_0014_teching_0016_auto_20240205_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='teching',
            name='sub',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='improvements',
            name='Learning',
            field=models.CharField(max_length=100),
        ),
    ]
