# Generated by Django 4.2.7 on 2024-02-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_teach_request_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teach_request',
        ),
    ]
